
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-02
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-02
pull_requests: [{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-course-details-visability","number":28,"title":"mb - add link to course's name to that navigates to details page","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/28"},{"author":{"id":"U_kgDOBYAf9w","is_bot":false,"login":"pewpewpew0","name":""},"headRefName":"ml-fix-backup-link","number":27,"title":"ml-Fix incorrect hard coded backup link (#22)","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/27"},{"author":{"id":"U_kgDOBdHq8Q","is_bot":false,"login":"fcataldothome","name":""},"headRefName":"personal_weekly","number":25,"title":"Personal weekly","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/25"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-no-courses-feedback","number":23,"title":"mb - 'No courses found' feedback for Courses Description Search","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/23"}]
