
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-02
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-02
pull_requests: [{"author":{"id":"U_kgDOBYAf9w","is_bot":false,"login":"pewpewpew0","name":""},"headRefName":"ml-react-eslint-rules","number":44,"title":"ml-react-eslint-rules: Reintroduce React ESLint rules and fix resulting lint errors","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/44"},{"author":{"id":"U_kgDOBdHq8Q","is_bot":false,"login":"fcataldothome","name":""},"headRefName":"remove_grade_history","number":43,"title":"Remove grade history","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/43"},{"author":{"id":"MDQ6VXNlcjcyMTY4MzQ5","is_bot":false,"login":"AgamMakkar21","name":""},"headRefName":"am-eslint-exception","number":41,"title":"am - fixed ESLint react-refresh exception and passes all tests","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/41"},{"author":{"id":"U_kgDOBdHq8Q","is_bot":false,"login":"fcataldothome","name":""},"headRefName":"personal_weekly","number":25,"title":"Personal weekly","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-02/pull/25"}]
